  version: "3"
services:
    postgres:
        build: containers/postgres/

    memcached:
        image: memcached:alpine

    rabbitmq:
        image: rabbitmq:alpine
        environment:
            - RABBITMQ_PASS=mypass
            - C_FORCE_ROOT=true
        ports:
            - "5672:5672"
            - "15672:15672"

    worker:
        build: containers/application/
        command: celery -A cohen worker -l info
        working_dir: /usr/src/app
        volumes:
            - ./cohen/:/usr/src/app
        environment:
            - C_FORCE_ROOT=true
            - BROKER_URL=amqp://guest:guest@rabbit:5672//
        env_file:
            - .env
        links:
            - rabbitmq:rabbit
        depends_on:
            - rabbitmq

    application:
        command: gunicorn --bind "0.0.0.0:8000" --workers 4 --reload cohen.wsgi
        working_dir: /usr/src/app
        volumes:
            - ./cohen/:/usr/src/app
        environment:
            - DJANGO_SETTINGS_MODULE=cohen.settings.production
        env_file:
            - .env
        links:
            - postgres
            - worker
            - memcached
        depends_on:
            - postgres

    nginx:
        image: nginx:alpine
        volumes:
            - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/cohen.conf:ro
        ports:
            - "80:8080"
        links:
            - application
